const data = {
  products: [
    {
      _id: "1",
      name: " Nike Sports Shoes",
      category: "Sports",
      image: "/images/p1.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4,
      numReviews: 10,
      description: "high quality Sports Shoes",
    },

    {
      _id: "2",
      name: "Amazon Alexa Voice AI ",
      category: "Voice AI",
      image: "/images/p2.jpg",
      price: 250,
      countInStock: 7,
      brand: "Amazon",
      rating: 4.5,
      numReviews: 10,
      description: "Amazon Echo smart speaker",
    },
    {
      _id: "3",
      name: "Puma Sneakers",
      category: "Sneakers",
      image: "/images/p3.jpg",
      price: 79.11,
      countInStock: 15,
      brand: "Puma",
      rating: 5,
      numReviews: 12,
      description: "Best Puma Shoes for Men ",
    },
    {
      _id: "4",
      name: "Apple AirPods Pro",
      category: "AirPods",
      image: "/images/p4.jpg",
      price: 180,
      countInStock: 22,
      brand: "Apple",
      rating: 4.5,
      numReviews: 10,
      description: "Wireless Bluetooth earbuds ",
    },
    {
      _id: "5",
      name: "Rayban Sunglass",
      category: "Sunglass",
      image: "/images/p5.jpg",
      price: 90,
      countInStock: 14,
      brand: "Rayban",
      rating: 4,
      numReviews: 20,
      description: "American Brand of Luxury Sunglasses",
    },
    {
      _id: "6",
      name: "Apple Smart Watch",
      category: "Watch",
      image: "/images/p6.jpg",
      price: 210,
      countInStock: 0,
      brand: "Apple",
      rating: 4.5,
      numReviews: 5,
      description: "Fourth Generation Apple Watch",
    },
    {
      _id: "7",
      name: "Beats by Dre",
      category: "Headphones",
      image: "/images/p7.jpg",
      price: 60,
      countInStock: 19,
      brand: "Beats",
      rating: 4.5,
      numReviews: 17,
      description: " Brings You the Best in Music",
    },
    {
      _id: "8",
      name: "Xbox Controller",
      category: "Controller",
      image: "/images/p8.jpg",
      price: 55.99,
      countInStock: 12,
      brand: "Xbox ",
      rating: 4.5,
      numReviews: 56,
      description: "Xbox Wireless Controller Emulator",
    },
    {
      _id: "9",
      name: "Nikon Package",
      category: "accessories",
      image: "/images/p9.jpg",
      price: 280,
      countInStock: 6,
      brand: "Nikon",
      rating: 4,
      numReviews: 2,
      description: "Essential Nikon DSLR Accessories",
    },
    {
      _id: "10",
      name: "Adidas Sneakers",
      category: "Sneakers",
      image: "/images/p10.jpg",
      price: 47,
      countInStock: 0,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 7,
      description: "adidas Skateboarding Sabalo",
    },
    {
      _id: "11",
      name: "Samsung Smartwatch",
      category: "Smartwatch",
      image: "/images/p11.jpg",
      price: 120,
      countInStock: 10,
      brand: "Samsung",
      rating: 5,
      numReviews: 17,
      description: " Best Samsung Watch in 2021",
    },
    {
      _id: "12",
      name: "Sony Playstation 5",
      category: "Playstation",
      image: "/images/p12.jpg",
      price: 120,
      countInStock: 10,
      brand: "Sony",
      rating: 4.5,
      numReviews: 41,
      description: "Home Video Game Console",
    },
  ],
};

export default data;
