const bcrypt = require("bcryptjs");

const data = {
  users: [
    {
      name: "Labbaek",
      email: "labbaekratul@gmail.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: true,
    },
    {
      name: "Roman",
      email: "user@gmail.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: false,
    },
  ],
  stores: [
    {
      name: "Walmart",
      image: "https://www.freepnglogos.com/uploads/walmart-logo-24.jpg",
      deliveryTime: "Delivery by 3:35pm",
      openingTime: "Monday - Friday (9am - 6pm)",
    },
    {
      name: "Adidas",
      image: "https://www.freepnglogos.com/uploads/walmart-logo-24.jpg",
      deliveryTime: "Delivery by 3:35pm",
      openingTime: "Monday - Friday (9am - 6pm)",
    },
    {
      name: "Amazon",
      image: "https://www.freepnglogos.com/uploads/walmart-logo-24.jpg",
      deliveryTime: "Delivery by 3:35pm",
      openingTime: "Monday - Friday (9am - 6pm)",
    },
    {
      name: "Apple",
      image: "https://www.freepnglogos.com/uploads/walmart-logo-24.jpg",
      deliveryTime: "Delivery by 3:35pm",
      openingTime: "Monday - Friday (9am - 6pm)",
    },
    {
      name: "Beats",
      image: "https://www.freepnglogos.com/uploads/walmart-logo-24.jpg",
      deliveryTime: "Delivery by 3:35pm",
      openingTime: "Monday - Friday (9am - 6pm)",
    },
    {
      name: "Nike",
      image: "https://www.freepnglogos.com/uploads/walmart-logo-24.jpg",
      deliveryTime: "Delivery by 3:35pm",
      openingTime: "Monday - Friday (9am - 6pm)",
    },
    {
      name: "Nikon",
      image: "https://www.freepnglogos.com/uploads/walmart-logo-24.jpg",
      deliveryTime: "Delivery by 3:35pm",
      openingTime: "Monday - Friday (9am - 6pm)",
    },
    {
      name: "Puma",
      image: "https://www.freepnglogos.com/uploads/walmart-logo-24.jpg",
      deliveryTime: "Delivery by 3:35pm",
      openingTime: "Monday - Friday (9am - 6pm)",
    },
    {
      name: "Rayban",
      image: "https://www.freepnglogos.com/uploads/walmart-logo-24.jpg",
      deliveryTime: "Delivery by 3:35pm",
      openingTime: "Monday - Friday (9am - 6pm)",
    },
    {
      name: "Samsung",
      image: "https://www.freepnglogos.com/uploads/walmart-logo-24.jpg",
      deliveryTime: "Delivery by 3:35pm",
      openingTime: "Monday - Friday (9am - 6pm)",
    },
    {
      name: "Slay station",
      image: "https://www.freepnglogos.com/uploads/walmart-logo-24.jpg",
      deliveryTime: "Delivery by 3:35pm",
      openingTime: "Monday - Friday (9am - 6pm)",
    },
    {
      name: "Xbox",
      image: "https://www.freepnglogos.com/uploads/walmart-logo-24.jpg",
      deliveryTime: "Delivery by 3:35pm",
      openingTime: "Monday - Friday (9am - 6pm)",
    },
  ],

  products: [
    {
      name: " Nike Sports Shoes",
      category: "Sports",
      image: "/images/p1.jpg",
      price: 120,
      countInStock: 10,
      store: "Nike",
      rating: 4,
      numReviews: 10,
      description: "high quality Sports Shoes",
    },

    {
      name: "Amazon Alexa Voice AI ",
      category: "Voice AI",
      image: "/images/p2.jpg",
      price: 250,
      countInStock: 7,
      store: "Amazon",
      rating: 4.5,
      numReviews: 10,
      description: "Amazon Echo smart speaker",
    },
    {
      name: "Puma Sneakers",
      category: "Sneakers",
      image: "/images/p3.jpg",
      price: 79.11,
      countInStock: 15,
      store: "Puma",
      rating: 5,
      numReviews: 12,
      description: "Best Puma Shoes for Men ",
    },
    {
      name: "Apple AirPods Pro",
      category: "AirPods",
      image: "/images/p4.jpg",
      price: 180,
      countInStock: 22,
      store: "Apple",
      rating: 4.5,
      numReviews: 10,
      description: "Wireless Bluetooth earbuds ",
    },
    {
      name: "Rayban Sunglass",
      category: "Sunglass",
      image: "/images/p5.jpg",
      price: 90,
      countInStock: 14,
      store: "Rayban",
      rating: 4,
      numReviews: 20,
      description: "American Brand of Luxury Sunglasses",
    },
    {
      name: "Apple Smart Watch",
      category: "Watch",
      image: "/images/p6.jpg",
      price: 210,
      countInStock: 0,
      store: "Apple",
      rating: 4.5,
      numReviews: 5,
      description: "Fourth Generation Apple Watch",
    },
    {
      name: "Beats by Dre",
      category: "Headphones",
      image: "/images/p7.jpg",
      price: 60,
      countInStock: 19,
      store: "Beats",
      rating: 4.5,
      numReviews: 17,
      description: " Brings You the Best in Music",
    },
    {
      name: "Xbox Controller",
      category: "Controller",
      image: "/images/p8.jpg",
      price: 55.99,
      countInStock: 12,
      store: "Xbox ",
      rating: 4.5,
      numReviews: 56,
      description: "Xbox Wireless Controller Emulator",
    },
    {
      name: "Nikon Package",
      category: "accessories",
      image: "/images/p9.jpg",
      price: 280,
      countInStock: 6,
      store: "Nikon",
      rating: 4,
      numReviews: 2,
      description: "Essential Nikon DSLR Accessories",
    },
    {
      name: "Adidas Sneakers",
      category: "Sneakers",
      image: "/images/p10.jpg",
      price: 47,
      countInStock: 0,
      store: "Adidas",
      rating: 4.5,
      numReviews: 7,
      description: "adidas Skateboarding Sabalo",
    },
    {
      name: "Samsung Smartwatch",
      category: "Smartwatch",
      image: "/images/p11.jpg",
      price: 120,
      countInStock: 10,
      store: "Samsung",
      rating: 5,
      numReviews: 17,
      description: " Best Samsung Watch in 2021",
    },
    {
      name: "Sony Playstation 5",
      category: "Playstation",
      image: "/images/p12.jpg",
      price: 120,
      countInStock: 10,
      store: "Sony",
      rating: 4.5,
      numReviews: 41,
      description: "Home Video Game Console",
    },
  ],
};

module.exports = data;
